### PR TITLE
Project: Background and gradients

### PR DESCRIPTION
**Pull request by taiwocoker**
### In this milestone, I added:
- A Navigation Bar
- A search Button
- Embedded Background Images and Gradients
- A footer

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @taiwocoker 
### You have done well so far :clap: However, you have a few issues to solve before the project could be approved.
- Make your thumbnails images fit the screen.
display of images
### Make the change and resubmit for another code review. Good luck.
- Happy coding!

**Comment by uryelah** [comment]
Hello **Taiwo Coker**, I'm Sarah, your reviewer for this PR 👩‍🚀  

For this project in specific, you are asked to make the main image to cover the whole width of the screen in any regardless of the screen size. Keep this in mind and try using styles that can help you reach that goal like percentages or vw widths. 
[Check this for more on CSS units.](https://www.w3schools.com/cssref/css_units.asp)

Fix the main issue and you'll be able to keep going to the next project, you can do it! 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] Make sure the bottom images are aligned with the main image. Always taking 100% of its width.
This is how it looks in my screen:
Screenshot_2020-04-08 Apple Page Clone(1)

---- 

- There's a margin between the main image and the bottom ones. Compare your version and the original one below:
Screenshot_2020-04-08 Apple Page Clone
Screenshot_2020-04-08 Apple

------

- [ ] Make sure the footer looks the same as the original one:
Screenshot_2020-04-08 Apple Page Clone(2)
Screenshot_2020-04-08 Apple(1)


----

- [ ] [OPTIONAL] On hover the whole nav link should change. It seems that your link is not taking 100% of its parent li. Compare it below:
navBtn
navBtnOriginal

-----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — APPROVED** [review]
### Hi @taiwocoker  👋

Good job here.👌

### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

- [ ] Optional - However to make your project look even better. Kindly add spaces between the three text elements at the page center.[Screenshot]👇
ice_screenshot_20200408-113832

Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
